### ISSUE TITLE
what does action space 'pose delta' mean?

### ISSUE THREAD

**Issue by ssvision** [sebbyjp/robo_transformers#52]
my current setup consists of a universal robot 6dof UR5e arm along with a onRobot gripper. There is a Intel Real Sense mounted on the head which is static. (assume it's a single arm humanoid robot with camera mounted on the head). Now when i run the model i.e pass an image and an instruction the model is supposed to output 7 values for the action space which are (x, y, z, roll, pitch, yaw, gripper state). My questions are as follows
1. The action space output from the transformer model i.e the end effector pose. Is it defined in camera frame?
2. what are the pose values ? are they absolute values or delta values as i am a bit confused with the terminology being used in the README section?

**Comment by sebbyjp** [comment]
Hello, they are relative in the world frame for pose and absolute for gripper. This is the reason I made https://github.com/mbodiai/embodied-agents. Much clearer and smoother to interact with robotic transformers!
